<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_LBuYxqwService extends AppKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.LBuYxqw' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.LBuYxqw'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Mautic\MessengerBundle\MessageHandler\PageHitNotificationHandler(($container->services['Mautic\\PageBundle\\Entity\\PageRepository'] ?? $container->load('getPageRepositoryService')), ($container->services['Mautic\\PageBundle\\Entity\\HitRepository'] ?? $container->load('getHitRepositoryService')), ($container->services['Mautic\\LeadBundle\\Entity\\LeadRepository'] ?? $container->getLeadRepository2Service()), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->services['Mautic\\PageBundle\\Entity\\RedirectRepository'] ?? $container->getRedirectRepositoryService()), ($container->services['Mautic\\PageBundle\\Model\\PageModel'] ?? $container->getPageModelService())), []);
    }
}
