<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HwNMuuBService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.HwNMuuB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HwNMuuB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lead' => ['privates', '.errored..service_locator.HwNMuuB.Mautic\\LeadBundle\\Entity\\Lead', NULL, 'Cannot autowire service ".service_locator.HwNMuuB": it references class "Mautic\\LeadBundle\\Entity\\Lead" but no such service exists.'],
            'model' => ['services', 'Mautic\\EmailBundle\\Model\\EmailModel', 'getEmailModelService', false],
            'translator' => ['services', 'translator', 'getTranslator2Service', false],
        ], [
            'lead' => 'Mautic\\LeadBundle\\Entity\\Lead',
            'model' => 'Mautic\\EmailBundle\\Model\\EmailModel',
            'translator' => '?',
        ]);
    }
}
