<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3L79kTeService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.3L79kTe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3L79kTe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actionModel' => ['services', 'Mautic\\EmailBundle\\Model\\EmailActionModel', 'getEmailActionModelService', true],
            'categoryModel' => ['services', 'Mautic\\CategoryBundle\\Model\\CategoryModel', 'getCategoryModelService', false],
        ], [
            'actionModel' => 'Mautic\\EmailBundle\\Model\\EmailActionModel',
            'categoryModel' => 'Mautic\\CategoryBundle\\Model\\CategoryModel',
        ]);
    }
}
