<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fyb7ODTService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.fyb7ODT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fyb7ODT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'corePermissions' => ['services', 'mautic.security', 'getMautic_SecurityService', false],
            'model' => ['services', 'Mautic\\LeadBundle\\Model\\LeadModel', 'getLeadModelService', false],
        ], [
            'corePermissions' => '?',
            'model' => 'Mautic\\LeadBundle\\Model\\LeadModel',
        ]);
    }
}
