<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UoH47rpService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.uoH47rp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uoH47rp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'model' => ['services', 'Mautic\\ReportBundle\\Model\\ReportModel', 'getReportModelService', true],
        ], [
            'model' => 'Mautic\\ReportBundle\\Model\\ReportModel',
        ]);
    }
}
