<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SKX92OAService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.SKX92OA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SKX92OA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contactTracker' => ['services', 'mautic.tracker.contact', 'getMautic_Tracker_ContactService', false],
            'leadModel' => ['services', 'Mautic\\LeadBundle\\Model\\LeadModel', 'getLeadModelService', false],
            'mailHash' => ['services', 'Mautic\\EmailBundle\\Helper\\MailHashHelper', 'getMailHashHelperService', false],
            'model' => ['services', 'Mautic\\EmailBundle\\Model\\EmailModel', 'getEmailModelService', false],
        ], [
            'contactTracker' => '?',
            'leadModel' => 'Mautic\\LeadBundle\\Model\\LeadModel',
            'mailHash' => 'Mautic\\EmailBundle\\Helper\\MailHashHelper',
            'model' => 'Mautic\\EmailBundle\\Model\\EmailModel',
        ]);
    }
}
