<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XDrc5lrService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.XDrc5lr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XDrc5lr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'leadModel' => ['services', 'Mautic\\LeadBundle\\Model\\LeadModel', 'getLeadModelService', false],
        ], [
            'leadModel' => 'Mautic\\LeadBundle\\Model\\LeadModel',
        ]);
    }
}
