<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KkKDsVService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.Kk_kDsV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kk_kDsV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'randomHelper' => ['services', 'mautic.helper.random', 'getMautic_Helper_RandomService', false],
            'replyService' => ['services', 'Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply', 'getReplyService', true],
        ], [
            'randomHelper' => '?',
            'replyService' => 'Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply',
        ]);
    }
}
