<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TIoiDnService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator._TIoiDn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._TIoiDn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coreParametersHelper' => ['services', 'mautic.helper.core_parameters', 'getMautic_Helper_CoreParametersService', false],
            'integrationHelper' => ['services', 'mautic.helper.integration', 'getMautic_Helper_IntegrationService', false],
            'pointGroupModel' => ['services', 'Mautic\\PointBundle\\Model\\PointGroupModel', 'getPointGroupModelService', true],
        ], [
            'coreParametersHelper' => '?',
            'integrationHelper' => '?',
            'pointGroupModel' => 'Mautic\\PointBundle\\Model\\PointGroupModel',
        ]);
    }
}
