<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MQeH1HjService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.mQeH1Hj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mQeH1Hj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dateFromObject' => ['privates', '.errored..service_locator.mQeH1Hj.DateTimeImmutable', NULL, 'Cannot autowire service ".service_locator.mQeH1Hj": it references class "DateTimeImmutable" but no such service exists.'],
            'dateToObject' => ['privates', '.errored..service_locator.mQeH1Hj.DateTimeImmutable', NULL, 'Cannot autowire service ".service_locator.mQeH1Hj": it references class "DateTimeImmutable" but no such service exists.'],
            'entity' => ['privates', '.errored..service_locator.mQeH1Hj.Mautic\\CampaignBundle\\Entity\\Campaign', NULL, 'Cannot autowire service ".service_locator.mQeH1Hj": it references class "Mautic\\CampaignBundle\\Entity\\Campaign" but no such service exists.'],
        ], [
            'dateFromObject' => 'DateTimeImmutable',
            'dateToObject' => 'DateTimeImmutable',
            'entity' => 'Mautic\\CampaignBundle\\Entity\\Campaign',
        ]);
    }
}
