<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CDD9OlvService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.CDD9Olv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CDD9Olv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.CDD9Olv.Mautic\\EmailBundle\\Entity\\Email', NULL, 'Cannot autowire service ".service_locator.CDD9Olv": it references class "Mautic\\EmailBundle\\Entity\\Email" but no such service exists.'],
            'security' => ['services', 'mautic.security', 'getMautic_SecurityService', false],
        ], [
            'entity' => 'Mautic\\EmailBundle\\Entity\\Email',
            'security' => '?',
        ]);
    }
}
