<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GaJiAEmService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.GaJiAEm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GaJiAEm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'emailDependencies' => ['services', 'Mautic\\EmailBundle\\Stats\\EmailDependencies', 'getEmailDependenciesService', true],
        ], [
            'emailDependencies' => 'Mautic\\EmailBundle\\Stats\\EmailDependencies',
        ]);
    }
}
