<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_14OZubDService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.14OZubD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.14OZubD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dateFromObject' => ['privates', '.errored..service_locator.14OZubD.DateTimeImmutable', NULL, 'Cannot autowire service ".service_locator.14OZubD": it references class "DateTimeImmutable" but no such service exists.'],
            'dateToObject' => ['privates', '.errored..service_locator.14OZubD.DateTimeImmutable', NULL, 'Cannot autowire service ".service_locator.14OZubD": it references class "DateTimeImmutable" but no such service exists.'],
            'entity' => ['privates', '.errored..service_locator.14OZubD.Mautic\\EmailBundle\\Entity\\Email', NULL, 'Cannot autowire service ".service_locator.14OZubD": it references class "Mautic\\EmailBundle\\Entity\\Email" but no such service exists.'],
        ], [
            'dateFromObject' => 'DateTimeImmutable',
            'dateToObject' => 'DateTimeImmutable',
            'entity' => 'Mautic\\EmailBundle\\Entity\\Email',
        ]);
    }
}
