<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_78y6ZCnService extends AppKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.78y6ZCn' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.78y6ZCn'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(\Closure::fromCallable([0 => ($container->privates['Mautic\\MessengerBundle\\MessageHandler\\TestHandler'] ?? $container->load('getTestHandlerService')), 1 => 'handleHit']), ['method' => 'handleHit']);
    }
}
