<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5bOrYKQService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.5bOrYKQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5bOrYKQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'assetModel' => ['services', 'Mautic\\AssetBundle\\Model\\AssetModel', 'getAssetModelService', false],
            'parametersHelper' => ['services', 'mautic.helper.core_parameters', 'getMautic_Helper_CoreParametersService', false],
        ], [
            'assetModel' => 'Mautic\\AssetBundle\\Model\\AssetModel',
            'parametersHelper' => '?',
        ]);
    }
}
