<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TcqOKGtService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.TcqOKGt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TcqOKGt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fieldModel' => ['services', 'Mautic\\LeadBundle\\Model\\FieldModel', 'getFieldModel2Service', false],
            'leadModel' => ['services', 'Mautic\\LeadBundle\\Model\\LeadModel', 'getLeadModelService', false],
            'model' => ['services', 'Mautic\\EmailBundle\\Model\\EmailModel', 'getEmailModelService', false],
            'security' => ['services', 'mautic.security', 'getMautic_SecurityService', false],
        ], [
            'fieldModel' => 'Mautic\\LeadBundle\\Model\\FieldModel',
            'leadModel' => 'Mautic\\LeadBundle\\Model\\LeadModel',
            'model' => 'Mautic\\EmailBundle\\Model\\EmailModel',
            'security' => '?',
        ]);
    }
}
