<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2u37lIgService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.2u37lIg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2u37lIg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'model' => ['services', 'Mautic\\AssetBundle\\Model\\AssetModel', 'getAssetModelService', false],
            'uploaderHelper' => ['services', 'oneup_uploader.templating.uploader_helper', 'getOneupUploader_Templating_UploaderHelperService', false],
        ], [
            'model' => 'Mautic\\AssetBundle\\Model\\AssetModel',
            'uploaderHelper' => '?',
        ]);
    }
}
