<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Hhcurh6Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.Hhcurh6' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\EmailBundle\\Model\\EmailModel'] ?? $container->getEmailModelService());

        if (isset($container->privates['.messenger.handler_descriptor.Hhcurh6'])) {
            return $container->privates['.messenger.handler_descriptor.Hhcurh6'];
        }

        return $container->privates['.messenger.handler_descriptor.Hhcurh6'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Mautic\MessengerBundle\MessageHandler\EmailHitNotificationHandler($a, ($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)))), []);
    }
}
