<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_MQeH1Hj_DateTimeImmutableService extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.mQeH1Hj.DateTimeImmutable' shared service.
     *
     * @return \DateTimeImmutable
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mQeH1Hj": it references class "DateTimeImmutable" but no such service exists.');
    }
}
