<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EyKoib5Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.eyKoib5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eyKoib5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'email' => ['privates', 'messenger.transport.email', 'getMessenger_Transport_EmailService', true],
            'failed' => ['privates', 'messenger.transport.failed', 'getMessenger_Transport_FailedService', true],
            'hit' => ['privates', 'messenger.transport.hit', 'getMessenger_Transport_HitService', true],
            'messenger.transport.email' => ['privates', 'messenger.transport.email', 'getMessenger_Transport_EmailService', true],
            'messenger.transport.failed' => ['privates', 'messenger.transport.failed', 'getMessenger_Transport_FailedService', true],
            'messenger.transport.hit' => ['privates', 'messenger.transport.hit', 'getMessenger_Transport_HitService', true],
        ], [
            'email' => '?',
            'failed' => '?',
            'hit' => '?',
            'messenger.transport.email' => '?',
            'messenger.transport.failed' => '?',
            'messenger.transport.hit' => '?',
        ]);
    }
}
