<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NVrFW2FService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.NVrFW2F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NVrFW2F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['services', 'Mautic\\EmailBundle\\Helper\\MailHelper', 'getMailHelperService', false],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
        ], [
            'mailer' => 'Mautic\\EmailBundle\\Helper\\MailHelper',
            'serializer' => '?',
        ]);
    }
}
