<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XTfq2ccService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.xTfq2cc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xTfq2cc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'assetsHelper' => ['services', 'Mautic\\CoreBundle\\Twig\\Helper\\AssetsHelper', 'getAssetsHelperService', false],
            'coreParametersHelper' => ['services', 'mautic.helper.core_parameters', 'getMautic_Helper_CoreParametersService', false],
            'emailConfig' => ['services', 'Mautic\\EmailBundle\\Helper\\EmailConfig', 'getEmailConfigService', true],
            'model' => ['services', 'Mautic\\EmailBundle\\Model\\EmailModel', 'getEmailModelService', false],
            'routerHelper' => ['services', 'router', 'getRouterService', false],
            'translator' => ['services', 'Mautic\\CoreBundle\\Translation\\Translator', 'getTranslatorService', false],
        ], [
            'assetsHelper' => 'Mautic\\CoreBundle\\Twig\\Helper\\AssetsHelper',
            'coreParametersHelper' => '?',
            'emailConfig' => 'Mautic\\EmailBundle\\Helper\\EmailConfig',
            'model' => 'Mautic\\EmailBundle\\Model\\EmailModel',
            'routerHelper' => '?',
            'translator' => 'Mautic\\CoreBundle\\Translation\\Translator',
        ]);
    }
}
