<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EnLA0uAService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.enLA0uA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.enLA0uA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fieldModel' => ['services', 'Mautic\\FormBundle\\Model\\FieldModel', 'getFieldModelService', false],
            'formUploader' => ['services', 'mautic.form.helper.form_uploader', 'getMautic_Form_Helper_FormUploaderService', false],
        ], [
            'fieldModel' => 'Mautic\\FormBundle\\Model\\FieldModel',
            'formUploader' => '?',
        ]);
    }
}
