<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L6WYyS3Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.l6WYyS3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l6WYyS3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'companyModel' => ['services', 'Mautic\\LeadBundle\\Model\\CompanyModel', 'getCompanyModelService', false],
            'fieldModel' => ['services', 'Mautic\\FormBundle\\Model\\FieldModel', 'getFieldModelService', false],
        ], [
            'companyModel' => 'Mautic\\LeadBundle\\Model\\CompanyModel',
            'fieldModel' => 'Mautic\\FormBundle\\Model\\FieldModel',
        ]);
    }
}
