<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnonymizeIpCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Command\AnonymizeIpCommand' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Command\AnonymizeIpCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Command\\AnonymizeIpCommand'] = new \Mautic\CoreBundle\Command\AnonymizeIpCommand(($container->services['Mautic\\CoreBundle\\Entity\\IpAddressRepository'] ?? $container->load('getIpAddressRepositoryService')), ($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))), ($container->services['Mautic\\CoreBundle\\Entity\\AuditLogRepository'] ?? $container->load('getAuditLogRepositoryService')));
    }
}
