<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalyseCustomFieldCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Field\Command\AnalyseCustomFieldCommand' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Field\Command\AnalyseCustomFieldCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Field\\Command\\AnalyseCustomFieldCommand'] = new \Mautic\LeadBundle\Field\Command\AnalyseCustomFieldCommand(($container->services['Mautic\\LeadBundle\\Model\\FieldModel'] ?? $container->getFieldModel2Service()), ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? $container->getLeadModelService()), ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
