<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbortColumnUpdateExceptionService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Field\Exception\AbortColumnUpdateException' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Field\Exception\AbortColumnUpdateException
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Field\\Exception\\AbortColumnUpdateException'] = new \Mautic\LeadBundle\Field\Exception\AbortColumnUpdateException();
    }
}
