<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBounceService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\MonitoredEmail\Processor\Bounce' shared autowired service.
     *
     * @return \Mautic\EmailBundle\MonitoredEmail\Processor\Bounce
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\EmailBundle\\Model\\EmailStatModel'] ?? $container->getEmailStatModelService());

        if (isset($container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Bounce'])) {
            return $container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Bounce'];
        }
        $b = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? $container->getLeadModelService());

        if (isset($container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Bounce'])) {
            return $container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Bounce'];
        }

        return $container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Bounce'] = new \Mautic\EmailBundle\MonitoredEmail\Processor\Bounce(($container->privates['mailer.default_transport'] ?? $container->load('getMailer_DefaultTransportService')), ($container->services['mautic.message.search.contact'] ?? $container->load('getMautic_Message_Search_ContactService')), $a, $b, ($container->services['translator'] ?? $container->getTranslator2Service()), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->services['Mautic\\LeadBundle\\Model\\DoNotContact'] ?? $container->getDoNotContactService()));
    }
}
