<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactExportAuditLogSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\EventListener\ContactExportAuditLogSubscriber' shared autowired service.
     *
     * @return \Mautic\LeadBundle\EventListener\ContactExportAuditLogSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CoreBundle\\Model\\AuditLogModel'] ?? $container->getAuditLogModelService());

        if (isset($container->services['Mautic\\LeadBundle\\EventListener\\ContactExportAuditLogSubscriber'])) {
            return $container->services['Mautic\\LeadBundle\\EventListener\\ContactExportAuditLogSubscriber'];
        }

        return $container->services['Mautic\\LeadBundle\\EventListener\\ContactExportAuditLogSubscriber'] = new \Mautic\LeadBundle\EventListener\ContactExportAuditLogSubscriber($a, ($container->services['mautic.helper.ip_lookup'] ?? $container->getMautic_Helper_IpLookupService()));
    }
}
