<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanupMediaAssetsCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Command\CleanupMediaAssetsCommand' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Command\CleanupMediaAssetsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Command\\CleanupMediaAssetsCommand'] = new \Mautic\CoreBundle\Command\CleanupMediaAssetsCommand(($container->services['mautic.helper.paths'] ?? $container->getMautic_Helper_PathsService()));
    }
}
