<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCacheInvalidateSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\EventListener\CacheInvalidateSubscriber' shared autowired service.
     *
     * @return \Mautic\CoreBundle\EventListener\CacheInvalidateSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\EventListener\\CacheInvalidateSubscriber'] = new \Mautic\CoreBundle\EventListener\CacheInvalidateSubscriber(($container->privates['doctrine.orm.default_configuration'] ?? $container->getDoctrine_Orm_DefaultConfigurationService()));
    }
}
