<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigType15Service extends AppKernelProdContainer
{
    /*
     * Gets the private 'Mautic\MessengerBundle\Form\Type\ConfigType' shared autowired service.
     *
     * @return \Mautic\MessengerBundle\Form\Type\ConfigType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Mautic\\MessengerBundle\\Form\\Type\\ConfigType'] = new \Mautic\MessengerBundle\Form\Type\ConfigType(($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
