<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanupCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\IntegrationsBundle\Command\CleanupCommand' shared autowired service.
     *
     * @return \Mautic\IntegrationsBundle\Command\CleanupCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\IntegrationsBundle\\Command\\CleanupCommand'] = new \Mautic\IntegrationsBundle\Command\CleanupCommand(($container->services['Mautic\\IntegrationsBundle\\Entity\\FieldChangeRepository'] ?? $container->load('getFieldChangeRepositoryService')));
    }
}
