<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignService extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.HsQty84.Mautic\CampaignBundle\Entity\Campaign' shared service.
     *
     * @return \Mautic\CampaignBundle\Entity\Campaign
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HsQty84": it references class "Mautic\\CampaignBundle\\Entity\\Campaign" but no such service exists.');
    }
}
