<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticSocialBundle\EventListener\ConfigSubscriber' shared autowired service.
     *
     * @return \MauticPlugin\MauticSocialBundle\EventListener\ConfigSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['MauticPlugin\\MauticSocialBundle\\Integration\\Config'] ?? $container->load('getConfigService'));

        if (isset($container->services['MauticPlugin\\MauticSocialBundle\\EventListener\\ConfigSubscriber'])) {
            return $container->services['MauticPlugin\\MauticSocialBundle\\EventListener\\ConfigSubscriber'];
        }

        return $container->services['MauticPlugin\\MauticSocialBundle\\EventListener\\ConfigSubscriber'] = new \MauticPlugin\MauticSocialBundle\EventListener\ConfigSubscriber($a);
    }
}
