<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignEventSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\EventListener\CampaignEventSubscriber' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\EventListener\CampaignEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.campaign.helper.notification'] ?? $container->load('getMautic_Campaign_Helper_NotificationService'));

        if (isset($container->services['Mautic\\CampaignBundle\\EventListener\\CampaignEventSubscriber'])) {
            return $container->services['Mautic\\CampaignBundle\\EventListener\\CampaignEventSubscriber'];
        }

        return $container->services['Mautic\\CampaignBundle\\EventListener\\CampaignEventSubscriber'] = new \Mautic\CampaignBundle\EventListener\CampaignEventSubscriber(($container->services['Mautic\\CampaignBundle\\Entity\\EventRepository'] ?? $container->load('getEventRepositoryService')), $a, ($container->services['Mautic\\CampaignBundle\\Entity\\CampaignRepository'] ?? $container->load('getCampaignRepositoryService')));
    }
}
