<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignEventDeleteSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\EventListener\CampaignEventDeleteSubscriber' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\EventListener\CampaignEventDeleteSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CampaignBundle\\Model\\CampaignModel'] ?? $container->getCampaignModelService());

        if (isset($container->services['Mautic\\CampaignBundle\\EventListener\\CampaignEventDeleteSubscriber'])) {
            return $container->services['Mautic\\CampaignBundle\\EventListener\\CampaignEventDeleteSubscriber'];
        }
        $b = ($container->services['Mautic\\CampaignBundle\\Model\\EventModel'] ?? $container->load('getEventModelService'));

        if (isset($container->services['Mautic\\CampaignBundle\\EventListener\\CampaignEventDeleteSubscriber'])) {
            return $container->services['Mautic\\CampaignBundle\\EventListener\\CampaignEventDeleteSubscriber'];
        }

        return $container->services['Mautic\\CampaignBundle\\EventListener\\CampaignEventDeleteSubscriber'] = new \Mautic\CampaignBundle\EventListener\CampaignEventDeleteSubscriber(($container->services['Mautic\\CampaignBundle\\Entity\\LeadEventLogRepository'] ?? $container->getLeadEventLogRepositoryService()), ($container->services['Mautic\\CampaignBundle\\Helper\\CampaignConfig'] ?? $container->load('getCampaignConfigService')), $a, $b);
    }
}
