<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignEventPointTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Form\Type\CampaignEventPointType' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Form\Type\CampaignEventPointType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.lead.provider.typeOperator'] ?? $container->load('getMautic_Lead_Provider_TypeOperatorService'));

        if (isset($container->services['Mautic\\LeadBundle\\Form\\Type\\CampaignEventPointType'])) {
            return $container->services['Mautic\\LeadBundle\\Form\\Type\\CampaignEventPointType'];
        }

        return $container->services['Mautic\\LeadBundle\\Form\\Type\\CampaignEventPointType'] = new \Mautic\LeadBundle\Form\Type\CampaignEventPointType($a);
    }
}
