<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignSubscriber6Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\DynamicContentBundle\EventListener\CampaignSubscriber' shared autowired service.
     *
     * @return \Mautic\DynamicContentBundle\EventListener\CampaignSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\DynamicContentBundle\\Model\\DynamicContentModel'] ?? $container->load('getDynamicContentModelService'));

        if (isset($container->services['Mautic\\DynamicContentBundle\\EventListener\\CampaignSubscriber'])) {
            return $container->services['Mautic\\DynamicContentBundle\\EventListener\\CampaignSubscriber'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['Mautic\\DynamicContentBundle\\EventListener\\CampaignSubscriber'])) {
            return $container->services['Mautic\\DynamicContentBundle\\EventListener\\CampaignSubscriber'];
        }

        return $container->services['Mautic\\DynamicContentBundle\\EventListener\\CampaignSubscriber'] = new \Mautic\DynamicContentBundle\EventListener\CampaignSubscriber($a, ($container->services['mautic.cache.provider'] ?? $container->getMautic_Cache_ProviderService()), $b);
    }
}
