<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignConfigService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\Helper\CampaignConfig' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\Helper\CampaignConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CampaignBundle\\Helper\\CampaignConfig'] = new \Mautic\CampaignBundle\Helper\CampaignConfig(($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))));
    }
}
