<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignMapStatsControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\Controller\CampaignMapStatsController' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\Controller\CampaignMapStatsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Mautic\\CampaignBundle\\Controller\\CampaignMapStatsController'] = $instance = new \Mautic\CampaignBundle\Controller\CampaignMapStatsController(($container->services['Mautic\\CampaignBundle\\Model\\CampaignModel'] ?? $container->getCampaignModelService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->get_ServiceLocator_Mx0UMmYService())->withContext('Mautic\\CampaignBundle\\Controller\\CampaignMapStatsController', $container));

        return $instance;
    }
}
