<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDbRegexValidatorService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Form\Validator\Constraints\DbRegexValidator' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Form\Validator\Constraints\DbRegexValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\DbRegexValidator'])) {
            return $container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\DbRegexValidator'];
        }

        return $container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\DbRegexValidator'] = new \Mautic\LeadBundle\Form\Validator\Constraints\DbRegexValidator($a);
    }
}
