<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailListsValidatorService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\Validator\EmailListsValidator' shared autowired service.
     *
     * @return \Mautic\EmailBundle\Validator\EmailListsValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\EmailBundle\\Validator\\EmailListsValidator'] = new \Mautic\EmailBundle\Validator\EmailListsValidator();
    }
}
