<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailDependenciesService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\Stats\EmailDependencies' shared autowired service.
     *
     * @return \Mautic\EmailBundle\Stats\EmailDependencies
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CampaignBundle\\Model\\CampaignModel'] ?? $container->getCampaignModelService());

        if (isset($container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'])) {
            return $container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'];
        }
        $b = ($container->services['Mautic\\LeadBundle\\Model\\ListModel'] ?? $container->getListModelService());

        if (isset($container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'])) {
            return $container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'];
        }
        $c = ($container->services['Mautic\\FormBundle\\Model\\ActionModel'] ?? $container->getActionModelService());

        if (isset($container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'])) {
            return $container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'];
        }
        $d = ($container->services['Mautic\\PointBundle\\Model\\PointModel'] ?? $container->load('getPointModelService'));

        if (isset($container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'])) {
            return $container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'];
        }
        $e = ($container->services['Mautic\\PointBundle\\Model\\TriggerEventModel'] ?? $container->load('getTriggerEventModelService'));

        if (isset($container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'])) {
            return $container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'];
        }
        $f = ($container->services['Mautic\\ReportBundle\\Model\\ReportModel'] ?? $container->load('getReportModelService'));

        if (isset($container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'])) {
            return $container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'];
        }

        return $container->services['Mautic\\EmailBundle\\Stats\\EmailDependencies'] = new \Mautic\EmailBundle\Stats\EmailDependencies($a, $b, $c, $d, $e, $f);
    }
}
