<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailActionModelService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\Model\EmailActionModel' shared autowired service.
     *
     * @return \Mautic\EmailBundle\Model\EmailActionModel
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\EmailBundle\\Model\\EmailModel'] ?? $container->getEmailModelService());

        if (isset($container->services['Mautic\\EmailBundle\\Model\\EmailActionModel'])) {
            return $container->services['Mautic\\EmailBundle\\Model\\EmailActionModel'];
        }

        return $container->services['Mautic\\EmailBundle\\Model\\EmailActionModel'] = new \Mautic\EmailBundle\Model\EmailActionModel($a, ($container->services['Mautic\\EmailBundle\\Entity\\EmailRepository'] ?? $container->load('getEmailRepositoryService')), ($container->services['mautic.security'] ?? $container->getMautic_SecurityService()));
    }
}
