<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailService extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.14OZubD.Mautic\EmailBundle\Entity\Email' shared service.
     *
     * @return \Mautic\EmailBundle\Entity\Email
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.14OZubD": it references class "Mautic\\EmailBundle\\Entity\\Email" but no such service exists.');
    }
}
