<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExecuteEventCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\Command\ExecuteEventCommand' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\Command\ExecuteEventCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CampaignBundle\\Command\\ExecuteEventCommand'] = new \Mautic\CampaignBundle\Command\ExecuteEventCommand(($container->services['Mautic\\CampaignBundle\\Executioner\\ScheduledExecutioner'] ?? $container->load('getScheduledExecutionerService')), ($container->services['translator'] ?? $container->getTranslator2Service()), ($container->services['mautic.helper.twig.formatter'] ?? $container->getMautic_Helper_Twig_FormatterService()));
    }
}
