<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailDraftRepositoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\Entity\EmailDraftRepository' shared autowired service.
     *
     * @return \Mautic\EmailBundle\Entity\EmailDraftRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\EmailBundle\\Entity\\EmailDraftRepository'] = new \Mautic\EmailBundle\Entity\EmailDraftRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
