<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailListsService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\Validator\EmailLists' shared autowired service.
     *
     * @return \Mautic\EmailBundle\Validator\EmailLists
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\EmailBundle\\Validator\\EmailLists'] = new \Mautic\EmailBundle\Validator\EmailLists();
    }
}
