<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PointBundle\Form\Type\GroupType' shared autowired service.
     *
     * @return \Mautic\PointBundle\Form\Type\GroupType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\PointBundle\\Form\\Type\\GroupType'] = new \Mautic\PointBundle\Form\Type\GroupType();
    }
}
