<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupScoreSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PointBundle\EventListener\GroupScoreSubscriber' shared autowired service.
     *
     * @return \Mautic\PointBundle\EventListener\GroupScoreSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\PointBundle\\Model\\TriggerModel'] ?? $container->load('getTriggerModelService'));

        if (isset($container->services['Mautic\\PointBundle\\EventListener\\GroupScoreSubscriber'])) {
            return $container->services['Mautic\\PointBundle\\EventListener\\GroupScoreSubscriber'];
        }

        return $container->services['Mautic\\PointBundle\\EventListener\\GroupScoreSubscriber'] = new \Mautic\PointBundle\EventListener\GroupScoreSubscriber($a);
    }
}
