<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadService extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.HwNMuuB.Mautic\LeadBundle\Entity\Lead' shared service.
     *
     * @return \Mautic\LeadBundle\Entity\Lead
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HwNMuuB": it references class "Mautic\\LeadBundle\\Entity\\Lead" but no such service exists.');
    }
}
