<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLightsaml_Container_StoreService extends AppKernelProdContainer
{
    /*
     * Gets the private 'lightsaml.container.store' shared service.
     *
     * @return \LightSaml\SymfonyBridgeBundle\Bridge\Container\StoreContainer
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.security.saml.id_store'] ?? $container->load('getMautic_Security_Saml_IdStoreService'));

        if (isset($container->privates['lightsaml.container.store'])) {
            return $container->privates['lightsaml.container.store'];
        }

        return $container->privates['lightsaml.container.store'] = new \LightSaml\SymfonyBridgeBundle\Bridge\Container\StoreContainer(($container->services['Mautic\\UserBundle\\Security\\SAML\\Store\\Request\\RequestStateStore'] ?? $container->load('getRequestStateStoreService')), $a, ($container->privates['lightsaml.store.sso_state'] ?? $container->load('getLightsaml_Store_SsoStateService')));
    }
}
