<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLightsaml_Store_SsoStateService extends AppKernelProdContainer
{
    /*
     * Gets the private 'lightsaml.store.sso_state' shared service.
     *
     * @return \LightSaml\Store\Sso\SsoStateSessionStore
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['lightsaml.store.sso_state'] = new \LightSaml\Store\Sso\SsoStateSessionStore(($container->services['.container.private.session'] ?? $container->get_Container_Private_SessionService()), 'samlsso');
    }
}
