<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_HitService extends AppKernelProdContainer
{
    /*
     * Gets the private 'messenger.transport.hit' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['messenger.transport_factory'] ?? $container->load('getMessenger_TransportFactoryService'));

        if (isset($container->privates['messenger.transport.hit'])) {
            return $container->privates['messenger.transport.hit'];
        }

        return $container->privates['messenger.transport.hit'] = $a->createTransport($container->getEnv('urlencoded-dsn:MAUTIC_MESSENGER_DSN_HIT'), ['transport_name' => 'hit'], ($container->privates['messenger.transport.native_php_serializer'] ?? ($container->privates['messenger.transport.native_php_serializer'] = new \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer())));
    }
}
