<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Campaign_ContactFinder_KickoffService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.campaign.contact_finder.kickoff' shared service.
     *
     * @return \Mautic\CampaignBundle\Executioner\ContactFinder\KickoffContactFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.campaign.contact_finder.kickoff'] = new \Mautic\CampaignBundle\Executioner\ContactFinder\KickoffContactFinder(($container->services['Mautic\\LeadBundle\\Entity\\LeadRepository'] ?? $container->getLeadRepository2Service()), ($container->services['Mautic\\CampaignBundle\\Entity\\CampaignRepository'] ?? $container->load('getCampaignRepositoryService')), ($container->services['monolog.logger.mautic'] ?? $container->getMonolog_Logger_MauticService()));
    }
}
