<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_User_ManagerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.user.manager' shared service.
     *
     * @return \Doctrine\ORM\EntityManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.user.manager'] = ($container->services['doctrine'] ?? $container->getDoctrineService())->getManagerForClass('Mautic\\UserBundle\\Entity\\User');
    }
}
