<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Campaign_EventLoggerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.campaign.event_logger' shared service.
     *
     * @return \Mautic\CampaignBundle\Executioner\Logger\EventLogger
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.tracker.contact'] ?? $container->getMautic_Tracker_ContactService());

        if (isset($container->services['mautic.campaign.event_logger'])) {
            return $container->services['mautic.campaign.event_logger'];
        }
        $b = ($container->services['Mautic\\CampaignBundle\\Model\\SummaryModel'] ?? $container->load('getSummaryModelService'));

        if (isset($container->services['mautic.campaign.event_logger'])) {
            return $container->services['mautic.campaign.event_logger'];
        }

        return $container->services['mautic.campaign.event_logger'] = new \Mautic\CampaignBundle\Executioner\Logger\EventLogger(($container->services['mautic.helper.ip_lookup'] ?? $container->getMautic_Helper_IpLookupService()), $a, ($container->services['Mautic\\CampaignBundle\\Entity\\LeadEventLogRepository'] ?? $container->getLeadEventLogRepositoryService()), ($container->services['Mautic\\CampaignBundle\\Entity\\LeadRepository'] ?? $container->getLeadRepositoryService()), $b);
    }
}
