<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Campaign_Helper_InactivityService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.campaign.helper.inactivity' shared service.
     *
     * @return \Mautic\CampaignBundle\Executioner\Helper\InactiveHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.campaign.helper.inactivity'] = new \Mautic\CampaignBundle\Executioner\Helper\InactiveHelper(($container->services['mautic.campaign.scheduler'] ?? $container->load('getMautic_Campaign_SchedulerService')), ($container->services['mautic.campaign.contact_finder.inactive'] ?? $container->load('getMautic_Campaign_ContactFinder_InactiveService')), ($container->services['Mautic\\CampaignBundle\\Entity\\LeadEventLogRepository'] ?? $container->getLeadEventLogRepositoryService()), ($container->services['Mautic\\CampaignBundle\\Entity\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->services['monolog.logger.mautic'] ?? $container->getMonolog_Logger_MauticService()), ($container->services['mautic.campaign.helper.decision'] ?? $container->load('getMautic_Campaign_Helper_DecisionService')));
    }
}
