<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Report_Helper_ReportService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.report.helper.report' shared service.
     *
     * @return \Mautic\ReportBundle\Helper\ReportHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['mautic.report.helper.report'])) {
            return $container->services['mautic.report.helper.report'];
        }

        return $container->services['mautic.report.helper.report'] = new \Mautic\ReportBundle\Helper\ReportHelper($a);
    }
}
