<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotWeakService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\UserBundle\Form\Validator\Constraints\NotWeak' shared autowired service.
     *
     * @return \Mautic\UserBundle\Form\Validator\Constraints\NotWeak
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\UserBundle\\Form\\Validator\\Constraints\\NotWeak'] = new \Mautic\UserBundle\Form\Validator\Constraints\NotWeak();
    }
}
