<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOwnerNotFoundExceptionService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\Helper\Exception\OwnerNotFoundException' shared autowired service.
     *
     * @return \Mautic\EmailBundle\Helper\Exception\OwnerNotFoundException
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\EmailBundle\\Helper\\Exception\\OwnerNotFoundException'] = new \Mautic\EmailBundle\Helper\Exception\OwnerNotFoundException();
    }
}
