<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOptimisticLockSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\EventListener\OptimisticLockSubscriber' shared autowired service.
     *
     * @return \Mautic\CoreBundle\EventListener\OptimisticLockSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\EventListener\\OptimisticLockSubscriber'] = new \Mautic\CoreBundle\EventListener\OptimisticLockSubscriber();
    }
}
