<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOptimizedService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\Executioner\Scheduler\Mode\Optimized' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\Executioner\Scheduler\Mode\Optimized
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CampaignBundle\\Executioner\\Scheduler\\Mode\\Optimized'] = new \Mautic\CampaignBundle\Executioner\Scheduler\Mode\Optimized(($container->services['Mautic\\LeadBundle\\Services\\PeakInteractionTimer'] ?? $container->load('getPeakInteractionTimerService')));
    }
}
