<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeakInteractionTimerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Services\PeakInteractionTimer' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Services\PeakInteractionTimer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Services\\PeakInteractionTimer'] = new \Mautic\LeadBundle\Services\PeakInteractionTimer(($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))), ($container->services['Mautic\\EmailBundle\\Entity\\StatRepository'] ?? $container->load('getStatRepository3Service')), ($container->services['Mautic\\PageBundle\\Entity\\HitRepository'] ?? $container->load('getHitRepositoryService')), ($container->services['Mautic\\FormBundle\\Entity\\SubmissionRepository'] ?? $container->load('getSubmissionRepositoryService')), ($container->services['mautic.cache.provider'] ?? $container->getMautic_Cache_ProviderService()));
    }
}
