<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointGroupEventsService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PointBundle\PointGroupEvents' shared autowired service.
     *
     * @return \Mautic\PointBundle\PointGroupEvents
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\PointBundle\\PointGroupEvents'] = new \Mautic\PointBundle\PointGroupEvents();
    }
}
