<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageSubscriber6Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PageBundle\EventListener\PageSubscriber' shared autowired service.
     *
     * @return \Mautic\PageBundle\EventListener\PageSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CoreBundle\\Twig\\Helper\\AssetsHelper'] ?? $container->getAssetsHelperService());

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\PageSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\PageSubscriber'];
        }
        $b = ($container->services['Mautic\\CoreBundle\\Model\\AuditLogModel'] ?? $container->getAuditLogModelService());

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\PageSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\PageSubscriber'];
        }

        return $container->services['Mautic\\PageBundle\\EventListener\\PageSubscriber'] = new \Mautic\PageBundle\EventListener\PageSubscriber($a, ($container->services['mautic.helper.ip_lookup'] ?? $container->getMautic_Helper_IpLookupService()), $b);
    }
}
