<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResultCacheHelperService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Cache\ResultCacheHelper' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Cache\ResultCacheHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Cache\\ResultCacheHelper'] = new \Mautic\CoreBundle\Cache\ResultCacheHelper();
    }
}
