<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportSubscriber4Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\EventListener\ReportSubscriber' shared autowired service.
     *
     * @return \Mautic\CoreBundle\EventListener\ReportSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\EventListener\\ReportSubscriber'] = new \Mautic\CoreBundle\EventListener\ReportSubscriber(($container->services['mautic.security'] ?? $container->getMautic_SecurityService()));
    }
}
