<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSegmentDateService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Validator\Constraints\SegmentDate' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Validator\Constraints\SegmentDate
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Validator\\Constraints\\SegmentDate'] = new \Mautic\LeadBundle\Validator\Constraints\SegmentDate();
    }
}
