<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSerializerSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\GrapesJsBuilderBundle\EventSubscriber\SerializerSubscriber' shared autowired service.
     *
     * @return \MauticPlugin\GrapesJsBuilderBundle\EventSubscriber\SerializerSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel'] ?? $container->load('getGrapesJsBuilderModelService'));

        if (isset($container->services['MauticPlugin\\GrapesJsBuilderBundle\\EventSubscriber\\SerializerSubscriber'])) {
            return $container->services['MauticPlugin\\GrapesJsBuilderBundle\\EventSubscriber\\SerializerSubscriber'];
        }
        $b = ($container->services['grapesjsbuilder.config'] ?? $container->load('getGrapesjsbuilder_ConfigService'));

        if (isset($container->services['MauticPlugin\\GrapesJsBuilderBundle\\EventSubscriber\\SerializerSubscriber'])) {
            return $container->services['MauticPlugin\\GrapesJsBuilderBundle\\EventSubscriber\\SerializerSubscriber'];
        }

        return $container->services['MauticPlugin\\GrapesJsBuilderBundle\\EventSubscriber\\SerializerSubscriber'] = new \MauticPlugin\GrapesJsBuilderBundle\EventSubscriber\SerializerSubscriber($a, $b);
    }
}
