<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTableNotFoundExceptionService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Segment\Exception\TableNotFoundException' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Segment\Exception\TableNotFoundException
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Segment\\Exception\\TableNotFoundException'] = new \Mautic\LeadBundle\Segment\Exception\TableNotFoundException();
    }
}
