<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnlinkService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Predis\Command\Unlink' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Predis\Command\Unlink
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Predis\\Command\\Unlink'] = new \Mautic\CoreBundle\Predis\Command\Unlink();
    }
}
