<?php

namespace ContainerH7AapXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidateEventCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\Command\ValidateEventCommand' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\Command\ValidateEventCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CampaignBundle\\Command\\ValidateEventCommand'] = new \Mautic\CampaignBundle\Command\ValidateEventCommand(($container->services['Mautic\\CampaignBundle\\Executioner\\InactiveExecutioner'] ?? $container->load('getInactiveExecutionerService')), ($container->services['translator'] ?? $container->getTranslator2Service()), ($container->services['mautic.helper.twig.formatter'] ?? $container->getMautic_Helper_Twig_FormatterService()));
    }
}
