<?php

namespace Proxies\__CG__\Mautic\EmailBundle\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EmailDraft extends \Mautic\EmailBundle\Entity\EmailDraft implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\EmailDraft' . "\0" . 'id', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\EmailDraft' . "\0" . 'email', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\EmailDraft' . "\0" . 'html', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\EmailDraft' . "\0" . 'template', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\EmailDraft' . "\0" . 'publicPreview'];
        }

        return ['__isInitialized__', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\EmailDraft' . "\0" . 'id', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\EmailDraft' . "\0" . 'email', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\EmailDraft' . "\0" . 'html', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\EmailDraft' . "\0" . 'template', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\EmailDraft' . "\0" . 'publicPreview'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EmailDraft $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function cleanUrlsInContent(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cleanUrlsInContent', []);

        parent::cleanUrlsInContent();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): \Mautic\EmailBundle\Entity\Email
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getHtml(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHtml', []);

        return parent::getHtml();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(\Mautic\EmailBundle\Entity\Email $email): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setHtml(string $html): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHtml', [$html]);

        parent::setHtml($html);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemplate(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemplate', []);

        return parent::getTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemplate(string $template): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemplate', [$template]);

        parent::setTemplate($template);
    }

    /**
     * {@inheritDoc}
     */
    public function isPublicPreview(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublicPreview', []);

        return parent::isPublicPreview();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishStatus(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishStatus', []);

        return parent::getPublishStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicPreview(bool $publicPreview): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicPreview', [$publicPreview]);

        parent::setPublicPreview($publicPreview);
    }

}
